### ISSUE TITLE
Неверное суммирование времени, проведенного в ОДНОЙ игре жанра

### ISSUE THREAD

**Issue by Keevic-Kurlick** [denelena/javaqa-team-diplom#1]
**Метка метода**
https://github.com/denelena/javaqa-team-diplom/blob/708ba4ce347a879c9f48127bde46c18af567168b/src/main/java/ru/netology/Player.java#L45

**Метка тестового метода**
https://github.com/denelena/javaqa-team-diplom/blob/708ba4ce347a879c9f48127bde46c18af567168b/src/test/java/ru/netology/PlayerTest.java#L19

**Описание**
Метод sumGenre класса Player не суммирует время по жанру, проведенное в одной игре. Выводит нулевой результат.

**Шаги воспроизведения**
В тестовом методе:
1.  Создать объект класса Player;
2.  Создать объект класса Game;
3. Вызвать метод installGame объекта Player, передать в него объект класса Game (созданную игру);
4. Вызвать метод play объекта Player, передать в него ранее созданную игру и время (в примере - 3 часа);
5. Вызвать метод sumGenre объекта Player, передать в него жанр ранее созданной игры; 
6. Отладить  метод.

**Ожидаемый результат**
Вывод метода sumGenre - 3. 

**Фактический результат**
Вывод метода sumGenre - 0.

**Окружение**
- Windows 10
- IntelliJ IDEA 2021.3.2 (Community Edition)

**Скриншот** 
![однаиграбаг](https://user-images.githubusercontent.com/73889874/162236602-284e6500-ec0d-46b1-8398-36a0c8dd1f4e.png)

@denelena

**Comment by denelena** [comment]
**Отчет по баг-репорту**
Баг исправлен. Тест проходит


**Скриншоты теста**
![fix1](https://user-images.githubusercontent.com/98104210/163111054-bb03c040-5777-4b98-9c58-0d149dffe4af.png)
