### ISSUE TITLE
Неправильно работает проверка наличия игры в каталоге для последней добавленной игры

### ISSUE THREAD

**Issue by denelena** [denelena/javaqa-team-diplom#10]
**Метка метода**
https://github.com/denelena/javaqa-team-diplom/blob/63526d48127fc505c5c4cbe5adc112baf7440552/src/main/java/ru/netology/GameStore.java#L32

**Метка тестового метода**
https://github.com/denelena/javaqa-team-diplom/blob/63526d48127fc505c5c4cbe5adc112baf7440552/src/test/java/ru/netology/GameStoreTest.java#L43

**Описание**
Метод containsGame класса GameStore возвращает неправильный результат для последней добавленной игры

**Шаги воспроизведения**
В тестовом методе:
1. Создать объект класса GameStore ;
2. Вызвать несколько раз метод publishGame объекта GameStore, передать в него необходимые параметры для создания игр;
3. Вызвать метод containsGame объекта GameStore, передать в него последнюю игру, созданную на шаге 2;

**Ожидаемый результат**
Вывод метода containsGame - true. 

**Фактический результат**
Вывод метода containsGame - false.

**Окружение**
- Windows 10
- IntelliJ IDEA 2021.3.2 (Community Edition)

**Скриншот**
![isuue10](https://user-images.githubusercontent.com/98104210/162491113-67d6b653-02e0-4c67-8b20-46e6c5946b65.png)

**Comment by Keevic-Kurlick** [comment]
**Отчет по баг-репорту**

Баг исправила. Проверка наличия игры заработала.
Метка метода:
https://github.com/denelena/javaqa-team-diplom/blob/8e55e9b0f79f6777a139550e2a09d776969d12be/src/main/java/ru/netology/GameStore.java#L29

**Скриншоты теста**
![баг5](https://user-images.githubusercontent.com/73889874/162982233-8aa1e2c7-c946-41c4-b423-6dc6aba4fa8f.png)
