### ISSUE TITLE
Не происходит суммирования проигранного времени для конкретного игрока

### ISSUE THREAD

**Issue by denelena** [denelena/javaqa-team-diplom#11]
**Метка метода**
https://github.com/denelena/javaqa-team-diplom/blob/63526d48127fc505c5c4cbe5adc112baf7440552/src/main/java/ru/netology/GameStore.java#L46

**Метка тестового метода**
https://github.com/denelena/javaqa-team-diplom/blob/63526d48127fc505c5c4cbe5adc112baf7440552/src/test/java/ru/netology/GameStoreTest.java#L60

**Описание**
Метод addPlayTime класса GameStore не суммирует проигранное игроком время с ранее добавленным временем этого же игрока.

**Шаги воспроизведения**
В тестовом методе:
1. Создать объект класса GameStore ;
2. Вызвать несколько раз метод addPlayTime объекта GameStore, передать в него имя одного и того же игрока и количество наигранных им часов (в тесте - 12 и 18 часов);
3. Вызвать метод getSumPlayedTime объекта GameStore

**Ожидаемый результат**
Вывод метода getSumPlayedTime - 30. 

**Фактический результат**
Вывод метода containsGame - 0

**Окружение**
- Windows 10
- IntelliJ IDEA 2021.3.2 (Community Edition)

**Скриншот**
![isuue11](https://user-images.githubusercontent.com/98104210/162500559-e0c5d43a-78c6-40ab-bc83-f6057bc180ac.png)

**Comment by Keevic-Kurlick** [comment]
**Отчет по баг-репорту**

Баг исправила. 
Метка метода:
https://github.com/denelena/javaqa-team-diplom/blob/8e55e9b0f79f6777a139550e2a09d776969d12be/src/main/java/ru/netology/GameStore.java#L39

**Скриншоты теста:**
![баг4](https://user-images.githubusercontent.com/73889874/162981774-fa1b89ce-7d26-4cb4-ace1-6b0ca24d3510.png)
