### ISSUE TITLE
Поиск самого заигравшегося игрока выдает неправильное значение, когда игроки играли по 0 часов

### ISSUE THREAD

**Issue by denelena** [denelena/javaqa-team-diplom#12]
**Метка метода**
https://github.com/denelena/javaqa-team-diplom/blob/63526d48127fc505c5c4cbe5adc112baf7440552/src/main/java/ru/netology/GameStore.java#L58

**Метка тестового метода**
https://github.com/denelena/javaqa-team-diplom/blob/63526d48127fc505c5c4cbe5adc112baf7440552/src/test/java/ru/netology/GameStoreTest.java#L100

**Описание**
Метод getMostPlayer класса GameStore возвращает неправильный результат, когда игроки играли по 0 часов

**Шаги воспроизведения**
В тестовом методе:
1. Создать объект класса GameStore ;
2. Вызвать несколько раз метод addPlayTime объекта GameStore, передать в него необходимые параметры: разные имена игроков и 0 часов, потраченных на игры;
3. Вызвать метод getMostPlayer объекта GameStore;

**Ожидаемый результат**
Вывод метода getMostPlayer- имя первого игрока на шаге 2 ("Maniac"). 

**Фактический результат**
Вывод метода getMostPlayer- null.

**Окружение**
- Windows 10
- IntelliJ IDEA 2021.3.2 (Community Edition)

**Скриншот**
![isuue12](https://user-images.githubusercontent.com/98104210/162502992-0f1dad69-ac52-4e4e-a6c0-a935be1b7602.png)

**Comment by Keevic-Kurlick** [comment]
**Отчет по баг-репорту**

Баг исправила. 
Метка метода:
https://github.com/denelena/javaqa-team-diplom/blob/8e55e9b0f79f6777a139550e2a09d776969d12be/src/main/java/ru/netology/GameStore.java#L52

**Скриншоты теста:**
![баг3](https://user-images.githubusercontent.com/73889874/162981484-656705dc-1b9d-4859-84d0-ee0f0f945248.png)
