### ISSUE TITLE
Поиск самого заигравшегося игрока выдает неправильное значение, когда игроки играли по 0-1 часов

### ISSUE THREAD

**Issue by denelena** [denelena/javaqa-team-diplom#13]
**Метка метода**
https://github.com/denelena/javaqa-team-diplom/blob/63526d48127fc505c5c4cbe5adc112baf7440552/src/main/java/ru/netology/GameStore.java#L58

**Метка тестового метода**
https://github.com/denelena/javaqa-team-diplom/blob/63526d48127fc505c5c4cbe5adc112baf7440552/src/test/java/ru/netology/GameStoreTest.java#L113

**Описание**
Метод getMostPlayer класса GameStore возвращает неправильный результат, когда игроки играли по 0-1 часов

**Шаги воспроизведения**
В тестовом методе:
1. Создать объект класса GameStore ;
2. Вызвать несколько раз метод addPlayTime объекта GameStore, передать в него необходимые параметры: разные имена игроков и от 0 до 1 часов, потраченных на игры;
3. Вызвать метод getMostPlayer объекта GameStore;

**Ожидаемый результат**
Вывод метода getMostPlayer- имя первого игрока на шаге 2, который играл 1 час ("Psycho"). 

**Фактический результат**
Вывод метода getMostPlayer- null.

**Окружение**
- Windows 10
- IntelliJ IDEA 2021.3.2 (Community Edition)

**Скриншот**
![isuue13](https://user-images.githubusercontent.com/98104210/162506262-70eb00a7-37a2-4a54-998f-b71b2f78cc5e.png)

**Comment by Keevic-Kurlick** [comment]
**Отчет по баг-репорту**

Баг исправила. 
Метка метода:
https://github.com/denelena/javaqa-team-diplom/blob/8e55e9b0f79f6777a139550e2a09d776969d12be/src/main/java/ru/netology/GameStore.java#L52

**Скриншоты теста:**
![баг2](https://user-images.githubusercontent.com/73889874/162981071-cc0c3ccb-81d9-414b-911f-d0f324765d8c.png)
