### ISSUE TITLE
Суммирование общего времени игр каталога выдает неверный результат

### ISSUE THREAD

**Issue by denelena** [denelena/javaqa-team-diplom#14]
**Метка метода**
https://github.com/denelena/javaqa-team-diplom/blob/63526d48127fc505c5c4cbe5adc112baf7440552/src/main/java/ru/netology/GameStore.java#L75

**Метка тестового метода**
https://github.com/denelena/javaqa-team-diplom/blob/63526d48127fc505c5c4cbe5adc112baf7440552/src/test/java/ru/netology/GameStoreTest.java#L134

**Описание**
Метод getSumPlayedTime класса GameStore возвращает неправильный результат при наличии одного или нескольких игроков

**Шаги воспроизведения**
В тестовом методе:
1. Создать объект класса GameStore ;
2. Вызвать несколько раз метод addPlayTime объекта GameStore, передать в него необходимые параметры: разные имена игроков и разные количества часов, потраченных на игры;
3. Вызвать метод getSumPlayedTime объекта GameStore;

**Ожидаемый результат**
Вывод метода getSumPlayedTime - Сумма продолжительностей игр всех  игроков ( в тесте 80 часов). 

**Фактический результат**
Вывод метода getSumPlayedTime - 0.

**Окружение**
- Windows 10
- IntelliJ IDEA 2021.3.2 (Community Edition)

**Скриншот**
![isuue14](https://user-images.githubusercontent.com/98104210/162509261-23338549-e5bf-4a33-b14e-5bafe1a9666e.png)

**Comment by Keevic-Kurlick** [comment]
**Отчет по баг-репорту**
Баг исправила.
Метка кода: 
https://github.com/denelena/javaqa-team-diplom/blob/8e55e9b0f79f6777a139550e2a09d776969d12be/src/main/java/ru/netology/GameStore.java#L39
**Скриншоты тестов**
![баг1](https://user-images.githubusercontent.com/73889874/162980657-4410442f-d51b-4fb5-888e-fa3bcadcb87e.png)
