### ISSUE TITLE
Неверное суммирование времени, проведенного в ДВУХ и БОЛЕЕ играх одного жанра

### ISSUE THREAD

**Issue by Keevic-Kurlick** [denelena/javaqa-team-diplom#2]
**Метка метода**
https://github.com/denelena/javaqa-team-diplom/blob/708ba4ce347a879c9f48127bde46c18af567168b/src/main/java/ru/netology/Player.java#L45

**Метка тестового метода**
_Две игры:_
https://github.com/denelena/javaqa-team-diplom/blob/708ba4ce347a879c9f48127bde46c18af567168b/src/test/java/ru/netology/PlayerTest.java#L33
_Три игры:_
https://github.com/denelena/javaqa-team-diplom/blob/708ba4ce347a879c9f48127bde46c18af567168b/src/test/java/ru/netology/PlayerTest.java#L49

**Описание**
Метод sumGenre класса Player неверно суммирует время, проведенное в двух и более играх. Вместо суммы выводит последнее записанное значение.

**Шаги воспроизведения**
В тестовом методе:
1.  Создать объект класса Player;
2.  Создать два или более объекта класса Game с _одинаковым_ жанром;
3. Два или более раза вызвать метод installGame объекта Player, передать в них поочередно объекты класса Game (созданные игру);
4. Два или более раза вызвать метод play объекта Player, передать в него поочередно ранее созданные игры и время (в примере с двумя играми: 3 и 5; с тремя - 3, 5, 5);
5. Вызвать метод sumGenre объекта Player, передать в него жанр ранее созданных игр; 
6. Отладить  метод.

**Ожидаемый результат**
Вывод метода sumGenre по двум играм из примера - 8. 
По трем играм из примера - 13. 

**Фактический результат**
Вывод метода sumGenre - 5 (в обоих случаях - последние введенные значения времени).

**Окружение**
- Windows 10
- IntelliJ IDEA 2021.3.2 (Community Edition)

**Скриншот** 
![триигрыбаг](https://user-images.githubusercontent.com/73889874/162240440-332dde30-b18e-463c-b7f3-41b0411612f4.png)
![двеигрыбаг](https://user-images.githubusercontent.com/73889874/162241044-c2b35e94-5506-45a8-aef6-2c445988a3a0.png)

@denelena

**Comment by denelena** [comment]
**Замечание**
В этих тестах (shouldSumGenreIfTwoGames & shouldSumGenreIfThreeGames) есть неточности. Метод play вызывается для игр, которые не были установлены. При правильной реализации метода play при тестировании происходит RuntimeException и тест падает. Это **False Negative**

**Screenshot**
![test_problem](https://user-images.githubusercontent.com/98104210/163112266-f11f6ac5-5ee5-49b8-9b16-c84691fd8c4b.png)

**Comment by Keevic-Kurlick** [comment]
Неточности исправила. 
Метки:
https://github.com/denelena/javaqa-team-diplom/blob/160e69ff0effdb5134345d18e2fb81cfeec65735/src/test/java/ru/netology/PlayerTest.java#L33
https://github.com/denelena/javaqa-team-diplom/blob/160e69ff0effdb5134345d18e2fb81cfeec65735/src/test/java/ru/netology/PlayerTest.java#L49

**Comment by denelena** [comment]
Спасибо,
Уже лучше, но тесты все еще падают. 

**Причина**
Поскольку game относится к другому жанру, нежели game1 и game2, для shouldSumGenreIfTwoGames ожидаемый результат должен быть 5, а для shouldSumGenreIfThreeGames - 10.

**Screenshots**
![more_test_problem1](https://user-images.githubusercontent.com/98104210/163269603-d5b664b1-755f-497c-910b-712cc38365bd.png)
![more_test_problem2](https://user-images.githubusercontent.com/98104210/163269622-890b674a-eec4-4d33-ad09-38a6c23c79fa.png)

**Comment by Keevic-Kurlick** [comment]
> 

Все, теперь точно должно заработать 😁 
https://github.com/denelena/javaqa-team-diplom/blob/accd53c34db0e83b80995df9cf895419115c7cf5/src/test/java/ru/netology/PlayerTest.java#L33
https://github.com/denelena/javaqa-team-diplom/blob/accd53c34db0e83b80995df9cf895419115c7cf5/src/test/java/ru/netology/PlayerTest.java#L49

**Comment by denelena** [comment]
**Отчет по баг-репорту**
Спасибо, тест проходит


**Скриншоты теста**
![fix2_1](https://user-images.githubusercontent.com/98104210/163679305-335c4bd1-fe97-4e9f-8b96-618b3d0b7b7d.png)
![fix2_2](https://user-images.githubusercontent.com/98104210/163679312-05458da6-1aaa-48dd-8f53-77859f1c84bf.png)
