### ISSUE TITLE
Не суммируется время, проведенное в игре за ОДИН подход

### ISSUE THREAD

**Issue by Keevic-Kurlick** [denelena/javaqa-team-diplom#3]
**Метка метода**
https://github.com/denelena/javaqa-team-diplom/blob/708ba4ce347a879c9f48127bde46c18af567168b/src/main/java/ru/netology/Player.java#L33

**Метка тестового метода**
https://github.com/denelena/javaqa-team-diplom/blob/708ba4ce347a879c9f48127bde46c18af567168b/src/test/java/ru/netology/PlayerTest.java#L79

**Описание**
Результат работы единоразового вызова метода play объекта класса Player с переданным в него временем возвращает нулевое значение вместо времени, которое было передано.

**Шаги воспроизведения**
1. Создать объект класса Player;
2. Создать объект класса Game;
3. Вызвать метод installGame объекта Player, передать в него объект класса Game (созданную игру);
4. Вызвать метод play объекта Player, передать в него игру и время (в примере - 5);
5. Отладить метод.

**Ожидаемый результат**
Возвращаемое значение метода play - 5.

**Фактический результат**
Возвращаемое значение метода play - 0.

**Окружение**
- Windows 10
- IntelliJ IDEA 2021.3.2 (Community Edition)

**Скриншот**
![времяотоднойигры](https://user-images.githubusercontent.com/73889874/162246205-e9317d1a-7337-4a38-b463-c043236008e1.png)

@denelena

**Comment by denelena** [comment]
**Отчет по баг-репорту**
Баг исправлен. Тест проходит


**Скриншоты теста**
![fix3](https://user-images.githubusercontent.com/98104210/163113078-e0de4ae3-2c69-4b1e-8d8d-4ddd43e362ff.png)
