### ISSUE TITLE
Не суммируется время, проведенное в игре за НЕСКОЛЬКО подходов

### ISSUE THREAD

**Issue by Keevic-Kurlick** [denelena/javaqa-team-diplom#4]
**Метка метода**
https://github.com/denelena/javaqa-team-diplom/blob/708ba4ce347a879c9f48127bde46c18af567168b/src/main/java/ru/netology/Player.java#L33

**Метка тестового метода**
https://github.com/denelena/javaqa-team-diplom/blob/708ba4ce347a879c9f48127bde46c18af567168b/src/test/java/ru/netology/PlayerTest.java#L92

**Описание**
Результат работы многоразового вызова метода play объекта класса Player с переданными в него _одной и той же_ игрой и временем возвращает нулевое значение вместо суммы времен, которые были переданы.

**Шаги воспроизведения**
В тестовом методе:
1. Создать объект класса Player;
2. Создать объект класса Game;
3. Вызвать метод installGame объекта Player, передать в него объект класса Game (созданную игру);
4. Вызвать метод play объекта Player, передать в него игру и время (в примере - 10);
5. Повторно вызвать метод play объекта Player, передать в него ту же игру и время (в примере - 5);
6. Отладить метод.

**Ожидаемый результат**
Возвращаемое значение метода play - 15.

**Фактический результат**
Возвращаемое значение метода play - 0.

**Окружение**
- Windows 10
- IntelliJ IDEA 2021.3.2 (Community Edition)

**Скриншот**
![многоигрсумма](https://user-images.githubusercontent.com/73889874/162247283-b7dc5d05-07f0-42d8-81ce-e59c32ca96b1.png)

@denelena

**Comment by denelena** [comment]
**Отчет по баг-репорту**
Баг исправлен. Тест проходит


**Скриншоты теста**
![fix4](https://user-images.githubusercontent.com/98104210/163113332-ef70cb26-5e7b-48cc-92e2-37b3b5b250f0.png)
