### ISSUE TITLE
Не выбрасывается Runtime Exception при вызове метода play на неустановленную игру

### ISSUE THREAD

**Issue by Keevic-Kurlick** [denelena/javaqa-team-diplom#5]
**Метка метода**
https://github.com/denelena/javaqa-team-diplom/blob/708ba4ce347a879c9f48127bde46c18af567168b/src/main/java/ru/netology/Player.java#L33

**Метка тестового метода**
https://github.com/denelena/javaqa-team-diplom/blob/708ba4ce347a879c9f48127bde46c18af567168b/src/test/java/ru/netology/PlayerTest.java#L106

**Описание**
При вызове метода play и передаче в него объекта класса Game БЕЗ предварительного вызова метода installGame на объект игры _НЕ_ выкидывается исключение Runtime Exception.

**Шаги воспроизведения**
В тестовом методе:
1. Создать объект класса Player;
2. Создать объект класса Game;
3. Вызвать метод play объекта Player, передать в него объект Game и время (в примере - 5);
4. Отладить метод.

**Ожидаемый результат**
Вывод исключения Runtime Exception, завершение программы.

**Фактический результат**
Runtime Exception не выкидывается.

**Окружение**
- Windows 10
- IntelliJ IDEA 2021.3.2 (Community Edition)

**Скриншот**
![исключение](https://user-images.githubusercontent.com/73889874/162248804-82214230-d852-468a-9977-8a25444a2d19.png)

@denelena

**Comment by denelena** [comment]
**Отчет по баг-репорту**
Баг исправлен. Тест проходит


**Скриншоты теста**
![fix5](https://user-images.githubusercontent.com/98104210/163113639-078fc16c-f66f-4bce-89e9-c011749c721a.png)
