### ISSUE TITLE
После переустановки игры обнуляется время, проведенное в игре

### ISSUE THREAD

**Issue by Keevic-Kurlick** [denelena/javaqa-team-diplom#6]
**Метка метода**
https://github.com/denelena/javaqa-team-diplom/blob/708ba4ce347a879c9f48127bde46c18af567168b/src/main/java/ru/netology/Player.java#L24

**Метка тестового метода**
https://github.com/denelena/javaqa-team-diplom/blob/708ba4ce347a879c9f48127bde46c18af567168b/src/test/java/ru/netology/PlayerTest.java#L133

**Описание**
При переустановке игры (последовательный вызов installGame, play(), installGame) обнуляется переданное в метод play время. _!!!Баг сопряжен с багом метода sumGenre._

**Шаги воспроизведения**
В тестовом методе:
1. Создать объект класса Player;
2. Создать объект класса Game;
3. Вызвать метод installGame объекта Player, передать в него объект класса Game (созданную игру);
4. Вызвать метод play объекта Player, передать в него игру и время (в примере - 4);
5. Повторно вызвать метод installGame объекта Player, передать в него ту же игру.
6. Проверить сохраненное время вызовом метода sumGenre по жанру игры.

**Ожидаемый результат**
Возвращаемое значение метода play - 4.

**Фактический результат**
Возвращаемое значение метода play - 0.

**Окружение**
- Windows 10
- IntelliJ IDEA 2021.3.2 (Community Edition)

**Скриншот**
![переустановка](https://user-images.githubusercontent.com/73889874/162250534-065519c3-df49-46b2-8a0e-82a1b1c2c7d6.png)

@denelena

**Comment by denelena** [comment]
**Отчет по баг-репорту**
Баг исправлен. Тест проходит


**Скриншоты теста**
![fix6](https://user-images.githubusercontent.com/98104210/163114053-f8b83919-6471-4a37-9e4f-2bd0bd6e125d.png)
