### ISSUE TITLE
Не выводится популярная в жанре игра при ОДНОЙ игре жанра

### ISSUE THREAD

**Issue by Keevic-Kurlick** [denelena/javaqa-team-diplom#7]
**Метка метода**
https://github.com/denelena/javaqa-team-diplom/blob/708ba4ce347a879c9f48127bde46c18af567168b/src/main/java/ru/netology/Player.java#L59

**Метка тестового метода**
https://github.com/denelena/javaqa-team-diplom/blob/708ba4ce347a879c9f48127bde46c18af567168b/src/test/java/ru/netology/PlayerTest.java#L148

**Описание**
В результате работы метода mostPlayerByGenre после установки ОДНОЙ игры жанра возвращается NULL вместо установленной игры.

**Шаги воспроизведения**
В тестовом методе:
1. Создать объект класса Player;
2. Создать объект класса Game (в примере - game1);
3. Вызвать метод installGame объекта Player, передать в него объект класса Game (созданную игру);
4. Вызвать метод play объекта Player, передать в него игру и время;
5. Вызвать метод mostPlayerByGenre объекта Player, передать в него жанр ранее созданной игры (в примере - "Хоррор");
6. Отладить метод.

**Ожидаемый результат**
Возвращаемое значение метода mostPlayerByGenre - game1.

**Фактический результат**
Возвращаемое значение метода mostPlayerByGenre - NULL.

**Окружение**
- Windows 10
- IntelliJ IDEA 2021.3.2 (Community Edition)

**Скриншот**
![популярнаяиграодна](https://user-images.githubusercontent.com/73889874/162251959-bfd59b52-a862-4714-b800-461123e00530.png)

@denelena

**Comment by denelena** [comment]
**Отчет по баг-репорту**
Баг исправлен. Тест проходит


**Скриншоты теста**
![fix7](https://user-images.githubusercontent.com/98104210/163115279-1531213f-c5ab-4bcd-b117-7043c38bada7.png)
