### ISSUE TITLE
Не выводится популярная игра жанра из ДВУХ и БОЛЕЕ игр при неравном времени в игре

### ISSUE THREAD

**Issue by Keevic-Kurlick** [denelena/javaqa-team-diplom#8]
**Метка метода**
https://github.com/denelena/javaqa-team-diplom/blob/708ba4ce347a879c9f48127bde46c18af567168b/src/main/java/ru/netology/Player.java#L59

**Метка тестового метода**
_Две игры:_
https://github.com/denelena/javaqa-team-diplom/blob/708ba4ce347a879c9f48127bde46c18af567168b/src/test/java/ru/netology/PlayerTest.java#L162
_Три игры:_
https://github.com/denelena/javaqa-team-diplom/blob/708ba4ce347a879c9f48127bde46c18af567168b/src/test/java/ru/netology/PlayerTest.java#L178

**Описание**
В результате работы метода mostPlayerByGenre после установки нескольких игр одного жанра возвращается NULL вместо игры, в методе play на которую было передано бОльшее время.

**Шаги воспроизведения**
В тестовом методе:
1. Создать объект класса Player;
2. Создать два или более объекта класса Game (на примере двух игр: game1, game2; трех - game1, game2, game3);
3. Два или более раза вызвать метод installGame объекта Player, передать в него  поочередно ранее созданные объекты класса Game;
4. Два или более раза вызвать метод play объекта Player, передать в него поочередно созданные игры и время (в примере для двух игр: 5 и 3 часа; в примере для трех игр - 4, 5, 6 часов);
5. Вызвать метод mostPlayerByGenre объекта Player, передать в него жанр ранее созданных игр (в примере - "Хоррор");
6. Отладить метод.

**Ожидаемый результат**
Возвращаемое значение метода mostPlayerByGenre - game1 (при двух играх) / game3 (при трех играх).

**Фактический результат**
Возвращаемое значение метода mostPlayerByGenre - NULL.

**Окружение**
- Windows 10
- IntelliJ IDEA 2021.3.2 (Community Edition)

**Скриншоты**
![триигрыбольшее](https://user-images.githubusercontent.com/73889874/162253647-42ab1ce4-f99c-427a-b987-bb97b28a4b26.png)
![двеигрыбольшее](https://user-images.githubusercontent.com/73889874/162253969-b6af6a21-7a1d-4dad-9a01-3391d1b64dd4.png)

@denelena

**Comment by denelena** [comment]
**Отчет по баг-репорту**
Баг исправлен. Тест проходит


**Скриншоты теста**
![fix8](https://user-images.githubusercontent.com/98104210/163116105-b7db3bd1-a50b-45ad-8512-e3b82d83081f.png)
