### ISSUE TITLE
Неправильно работает проверка наличия игры в каталоге, при условии, что в каталог добавлена только одна игра.

### ISSUE THREAD

**Issue by denelena** [denelena/javaqa-team-diplom#9]
**Метка метода**
https://github.com/denelena/javaqa-team-diplom/blob/63526d48127fc505c5c4cbe5adc112baf7440552/src/main/java/ru/netology/GameStore.java#L32

**Метка тестового метода**
https://github.com/denelena/javaqa-team-diplom/blob/63526d48127fc505c5c4cbe5adc112baf7440552/src/test/java/ru/netology/GameStoreTest.java#L14

**Описание**
Метод containsGame класса GameStore возвращает неправильный результат при наличии в каталоге только одной игры

**Шаги воспроизведения**
В тестовом методе:
1.  Создать объект класса GameStore ;
2.  Вызвать метод publishGame объекта GameStore, передать в него необходимые параметры для создания игры;
3. Вызвать метод containsGame объекта GameStore, передать в него игру, созданную на шаге 2;

**Ожидаемый результат**
Вывод метода containsGame - true. 

**Фактический результат**
Вывод метода containsGame - false.

**Окружение**
- Windows 10
- IntelliJ IDEA 2021.3.2 (Community Edition)

**Скриншот**
![isuue9](https://user-images.githubusercontent.com/98104210/162488795-96fbc4b5-7fde-4324-9ba0-6d89284d5535.png)

**Comment by Keevic-Kurlick** [comment]
**Отчет по баг-репорту**
Баг исправила. Проверка игры работает.

Метка метода: 
https://github.com/denelena/javaqa-team-diplom/blob/8e55e9b0f79f6777a139550e2a09d776969d12be/src/main/java/ru/netology/GameStore.java#L29

**Скриншоты теста**
![баг6](https://user-images.githubusercontent.com/73889874/162982621-e34b89e5-87ea-46fa-8cbc-642534e91f67.png)
